output: ./dist/documentation
name: NgxMultiKeywordsHighlighter Documentation
# Configurations: https://compodoc.app/guides/options.html
tsconfig: tsconfig.doc.json
theme: material
version: 1.0.0
# language: en-US
# customFavicon: .storybook/favicon.ico
# customLogo: .storybook/logo.svg
hideGenerator: true
disablePrivate: true
disableInternal: true
# disableCoverage: true
