name: NgxMultiKeywordsHighlighter Documentation
version: 2.1.2
# Configurations: https://compodoc.app/guides/options.html
tsconfig: tsconfig.doc.json
theme: material
customFavicon: tools/assets/favicon.ico
customLogo: tools/assets/logo-light.svg
hideGenerator: true
disablePrivate: true
disableInternal: true
# disableCoverage: true
output: ./dist/compodoc
unitTestCoverage: ./dist/coverage/libs/ngx-multi-keywords-highlighter/coverage-summary.json