version: "3.8"

services:
  demo-storybook:
    image: nginx:latest
    restart: always
    ports:
      - "8091:8080"
    volumes:
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf
      - ./dist/storybook/demo:/usr/share/nginx/html

  mkh-storybook:
    image: nginx:latest
    restart: always
    ports:
      - "8092:8080"
    volumes:
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf
      - ./dist/storybook/ngx-multi-keywords-highlighter:/usr/share/nginx/html

  verdaccio:
    build:
      context: .
      dockerfile: ./verdaccio/Dockerfile
    restart: always
    environment:
      - VERDACCIO_PORT=4873
    ports:
      - "4873:4873"
    volumes:
      - "./verdaccio/conf/storage:/verdaccio/storage"
      - "./verdaccio/conf/plugins:/verdaccio/plugins"
      - "./verdaccio/conf:/verdaccio/conf"