version: 2.1
description: Circle CI
orbs:
  node: circleci/node@4.2.0
  browser-tools: circleci/browser-tools@1.1.3
jobs:
  test_library:
    executor:
      name: node/default
      tag: '15.10'
    steps:
      - checkout
      - browser-tools/install-chrome
      - node/install-packages
      - run:
          command: |
            google-chrome --version
            npm run test:lib:ci
          name: Unit test Angular Library
workflows:
  test_library:
    jobs:
      - test_library
