FROM verdaccio/verdaccio:latest

COPY verdaccio/conf/config.yaml /verdaccio/conf/config.yaml
COPY verdaccio/conf/logo.svg /opt/verdaccio/conf/logo.svg
COPY verdaccio/conf/favicon.ico /opt/verdaccio/conf/favicon.ico