FROM verdaccio/verdaccio:latest

COPY verdaccio/conf/config.yaml /verdaccio/conf/config.yaml
COPY tools/assets/logo.svg /opt/verdaccio/conf/logo.svg
COPY tools/assets/logo-light.svg /opt/verdaccio/conf/logo-light.svg
COPY tools/assets/favicon.ico /opt/verdaccio/conf/favicon.ico