# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish NGX Multi Keywords Highlighter

on:
  release:
    types: [published]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm run ngx-multi-keywords-highlighter:lint
      - run: npm run ngx-multi-keywords-highlighter:test
      - run: npx semantic-release --no-ci --debug=true --dry-run=true

  publish-npm:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org
      - run: git config --global user.email "${{ vars.RELEASE_USER_EMAIL }}"
      - run: git config --global user.name "${{ vars.RELEASE_USER_NAME }}"
      - run: npm ci
      - run: npm run ngx-multi-keywords-highlighter:build
      - name: Semantic Release 📦
        run: npx semantic-release --ci --debug=true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

