name: Test release for Feature branch

on:
  push:
    branches: [ 'feature/**' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.JS
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
      - name: Cache NPM packages
        id: cache-npm-packages
        uses: actions/cache@v3
        env:
          cache-name: cache-npm-packages
        with:
          path: ./node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
      - if: ${{ steps.cache-npm-packages.outputs.cache-hit != 'true' }}
        run: npm ci --ignore-scripts
      - name: Config Git User
        run: |
          git config --global user.email "${{ vars.RELEASE_USER_EMAIL }}"
          git config --global user.name "${{ vars.RELEASE_USER_NAME }}"
      - name: Lint
        run: npm run mkh:lint
      - name: Test
        run: npm run mkh:test
      - name: Build
        run: npm run mkh:build
      - name: Semantic Release 📦
        run: npx semantic-release --ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}