# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish NGX Multi Keywords Highlighter

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.JS
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
      - name: Clean Install
        run: npm ci
      - name: Lint
        run: npm run ngx-multi-keywords-highlighter:lint
      - name: Test
        run: npm run ngx-multi-keywords-highlighter:test
      - name: Build
        run: npm run ngx-multi-keywords-highlighter:build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Semantic DryRun
        run: npx semantic-release --ci --debug=true --dry-run=true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

  publish-npm:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.JS
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org
      - name: Config Git User
        run: |
          git config --global user.email "${{ vars.RELEASE_USER_EMAIL }}"
          git config --global user.name "${{ vars.RELEASE_USER_NAME }}"
      - name: Clean Install
        run: npm ci
      - name: Build
        run: npm run ngx-multi-keywords-highlighter:build
      - name: Semantic Release 📦
        run: npx semantic-release --ci --debug=true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}


