name: Publish NGX Multi Keywords Highlighter

on:
  push:
    branches:
      - main
      - develop
permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.JS
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
      - name: Cache NPM packages
        id: cache-npm-packages
        uses: actions/cache@v3
        env:
          cache-name: cache-npm-packages
        with:
          path: ./node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}
      - if: ${{ steps.cache-npm-packages.outputs.cache-hit != 'true' }}
        run: npm ci --ignore-scripts
      - name: Config Git User
        run: |
          git config --global user.email "${{ vars.RELEASE_USER_EMAIL }}"
          git config --global user.name "${{ vars.RELEASE_USER_NAME }}"
      - name: Lint
        run: npm run mkh:lint
      - name: Test
        run: npm run mkh:test
      - name: Build
        run: npm run mkh:build
      - name: Semantic Release 📦
        run: npx nx release --dry-run --first-release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}